print(100*'=')
print('Calcula Salário'.center(30))
SaldoHora = float(input('Quanto você ganha por hora:R$ '))
HorasTrabalhadas = float(input('Quantas horas você trabalhou este mês: '))
print(f'Neste mês você recebera R$ {SaldoHora*HorasTrabalhadas:.2f}')
print(100*'=')