print(100*'=')
print('Conversor de Temperaturas'.center(30))
TemperaturaFarenheit = int(input('Entre com a temperatura:ºF '))
TemperaturaCelsius = 5*((TemperaturaFarenheit-32)/9)
print(f'Temperatura: {TemperaturaCelsius:.2f}ºC')
print(100*'=')
